import { createServer } from 'node:http'
import { randomBytes, scryptSync, timingSafeEqual, createHmac } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const PORT = Number(process.env.PORT || 4000)
const DATA_FILE = process.env.DATA_FILE || resolve('server/data/store.json')
const JWT_SECRET = process.env.JWT_SECRET || 'development-only-change-me'
const isProduction = process.env.NODE_ENV === 'production'
const cookieSameSite = process.env.COOKIE_SAME_SITE || 'Lax'
const cookieSecure = process.env.COOKIE_SECURE === 'true' || isProduction
const sessionCookie = (token, maxAge) => `session=${token}; HttpOnly; SameSite=${cookieSameSite}; Path=/; Max-Age=${maxAge}${cookieSecure ? '; Secure' : ''}`
const now = () => new Date().toISOString()
const id = () => randomBytes(12).toString('hex')
const hash = (value) => { const salt = randomBytes(16).toString('hex'); return `${salt}:${scryptSync(value, salt, 64).toString('hex')}` }
const verify = (value, stored) => { const [salt, key] = stored.split(':'); const candidate = scryptSync(value, salt, 64); return timingSafeEqual(candidate, Buffer.from(key, 'hex')) }
const sign = (payload) => { const encoded = Buffer.from(JSON.stringify({ ...payload, exp: Date.now() + 1000 * 60 * 60 * 24 * 7 })).toString('base64url'); return `${encoded}.${createHmac('sha256', JWT_SECRET).update(encoded).digest('base64url')}` }
const readToken = (token) => { if (!token) return null; const [encoded, signature] = token.split('.'); if (!signature || !timingSafeEqual(Buffer.from(signature), Buffer.from(createHmac('sha256', JWT_SECRET).update(encoded).digest('base64url')))) return null; try { const value = JSON.parse(Buffer.from(encoded, 'base64url').toString()); return value.exp > Date.now() ? value : null } catch { return null } }
const publicUser = (user) => { const safe = { ...user }; delete safe.passwordHash; return safe }
const seed = () => ({
  users: [], categories: [
    { id: 'cat-tech', name: 'Technology', slug: 'technology', description: 'Modern work essentials', image: '', status: 'ACTIVE', createdAt: now(), updatedAt: now() },
    { id: 'cat-office', name: 'Office', slug: 'office', description: 'Thoughtful workspace tools', image: '', status: 'ACTIVE', createdAt: now(), updatedAt: now() },
  ],
  products: [
    { id: 'prod-keyboard', name: 'Mechanical Keyboard', slug: 'mechanical-keyboard', sku: 'KB-100', barcode: '100000000001', description: 'Tactile wireless keyboard for focused work.', categoryId: 'cat-tech', costPrice: 48, sellingPrice: 79, salePrice: 69, taxRate: 5, stockQuantity: 24, lowStockThreshold: 5, status: 'ACTIVE', featured: true, images: [], createdAt: now(), updatedAt: now() },
    { id: 'prod-lamp', name: 'Focus Desk Lamp', slug: 'focus-desk-lamp', sku: 'LP-200', barcode: '100000000002', description: 'Adjustable warm-light desk lamp.', categoryId: 'cat-office', costPrice: 24, sellingPrice: 42, salePrice: null, taxRate: 5, stockQuantity: 8, lowStockThreshold: 4, status: 'ACTIVE', featured: true, images: [], createdAt: now(), updatedAt: now() },
  ], carts: [], orders: [], coupons: [], wishlists: [], reviews: [], addresses: [], payments: [], inventory: [], taxSettings: [{ id: 'default-tax', name: 'Sales tax', percentage: 5, active: true }], settings: { storeName: 'ITMANGEMENT', email: 'hello@example.com', phone: '', address: '', currency: 'USD', shippingFee: 8, freeShippingThreshold: 100 }
})
function db() { if (!existsSync(DATA_FILE)) { mkdirSync(dirname(DATA_FILE), { recursive: true }); const store = seed(); const password = process.env.ADMIN_PASSWORD; if (process.env.ADMIN_EMAIL && password) store.users.push({ id: id(), name: process.env.ADMIN_NAME || 'Store Admin', email: process.env.ADMIN_EMAIL.toLowerCase(), phone: '', passwordHash: hash(password), role: 'ADMIN', status: 'ACTIVE', createdAt: now(), updatedAt: now() }); writeFileSync(DATA_FILE, JSON.stringify(store, null, 2)); } return JSON.parse(readFileSync(DATA_FILE, 'utf8')) }
function save(store) { mkdirSync(dirname(DATA_FILE), { recursive: true }); writeFileSync(DATA_FILE, JSON.stringify(store, null, 2)) }
const json = (res, status, data) => { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'strict-origin-when-cross-origin' }); res.end(JSON.stringify({ success: status < 400, ...data })) }
const body = (req) => new Promise((resolveBody, reject) => { let raw = ''; req.on('data', c => { raw += c; if (raw.length > 1_000_000) reject(new Error('Request body too large')) }); req.on('end', () => { try { resolveBody(raw ? JSON.parse(raw) : {}) } catch { reject(new Error('Invalid JSON request body')) } }) })
const cookie = (req, name) => Object.fromEntries((req.headers.cookie || '').split(';').map(x => x.trim().split('=')))[name]
const userFor = (req, store) => { const token = readToken(cookie(req, 'session') || req.headers.authorization?.replace('Bearer ', '')); return token ? store.users.find(user => user.id === token.id && user.status === 'ACTIVE') : null }
const requireUser = (req, res, store, admin = false) => { const user = userFor(req, store); if (!user) { json(res, 401, { error: { message: 'Authentication is required.' } }); return null } if (admin && user.role !== 'ADMIN') { json(res, 403, { error: { message: 'Administrator access is required.' } }); return null } return user }
const cartFor = (store, user) => { let cart = store.carts.find(c => c.userId === user.id); if (!cart) { cart = { id: id(), userId: user.id, items: [], createdAt: now(), updatedAt: now() }; store.carts.push(cart) } return cart }
const cartView = (store, cart) => ({ ...cart, items: cart.items.map(item => ({ ...item, product: store.products.find(p => p.id === item.productId) })).filter(item => item.product) })
const orderNumber = () => `ORD-${Date.now().toString(36).toUpperCase()}-${randomBytes(2).toString('hex').toUpperCase()}`
const totals = (store, cart, couponCode) => { const items = cart.items.map(i => { const p = store.products.find(x => x.id === i.productId && x.status === 'ACTIVE'); if (!p || p.stockQuantity < i.quantity) throw new Error(`Insufficient stock for ${p?.name || 'a cart item'}`); const price = p.salePrice ?? p.sellingPrice; return { product: p, quantity: i.quantity, price, tax: price * i.quantity * p.taxRate / 100 } }); const subtotal = items.reduce((sum, x) => sum + x.price * x.quantity, 0); const tax = items.reduce((sum, x) => sum + x.tax, 0); let discount = 0; let coupon; if (couponCode) { coupon = store.coupons.find(c => c.code.toUpperCase() === couponCode.toUpperCase()); if (!coupon || coupon.status !== 'ACTIVE' || new Date(coupon.startDate) > new Date() || new Date(coupon.endDate) < new Date() || (coupon.usageLimit && coupon.usedCount >= coupon.usageLimit) || subtotal < coupon.minimumOrder) throw new Error('Coupon is invalid or unavailable.'); discount = coupon.type === 'PERCENTAGE' ? subtotal * coupon.value / 100 : coupon.value; if (coupon.maximumDiscount) discount = Math.min(discount, coupon.maximumDiscount); discount = Math.min(discount, subtotal) } const shippingFee = subtotal >= store.settings.freeShippingThreshold ? 0 : store.settings.shippingFee; return { items, subtotal, tax, discount, shippingFee, total: subtotal + tax + shippingFee - discount, coupon } }

export function app(req, res) { const origin = req.headers.origin; if (origin && (!process.env.CORS_ORIGIN || origin === process.env.CORS_ORIGIN)) res.setHeader('Access-Control-Allow-Origin', origin); res.setHeader('Access-Control-Allow-Credentials', 'true'); if (req.method === 'OPTIONS') { res.writeHead(204, { 'Access-Control-Allow-Headers': 'Content-Type, Authorization', 'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS' }); return res.end() } const url = new URL(req.url, `http://${req.headers.host}`); const path = url.pathname; const store = db(); const run = async () => {
 try {
  if (req.method === 'GET' && path === '/api/health') return json(res, 200, { data: { status: 'ok' } });
  if (req.method === 'POST' && path === '/api/auth/register') { const b = await body(req); if (!b.name?.trim() || !/^\S+@\S+\.\S+$/.test(b.email || '') || !b.password || b.password.length < 8) return json(res, 422, { error: { message: 'Name, valid email, and an 8-character password are required.' } }); if (store.users.some(u => u.email === b.email.toLowerCase())) return json(res, 409, { error: { message: 'An account with this email already exists.' } }); const user = { id: id(), name: b.name.trim(), email: b.email.toLowerCase(), phone: b.phone?.trim() || '', passwordHash: hash(b.password), role: 'CUSTOMER', status: 'ACTIVE', createdAt: now(), updatedAt: now() }; store.users.push(user); save(store); res.setHeader('Set-Cookie', sessionCookie(sign({ id: user.id }), 604800)); return json(res, 201, { data: { user: publicUser(user) } }) }
  if (req.method === 'POST' && path === '/api/auth/login') { const b = await body(req); const user = store.users.find(u => u.email === String(b.email || '').toLowerCase()); if (!user || !verify(String(b.password || ''), user.passwordHash)) return json(res, 401, { error: { message: 'Invalid email or password.' } }); if (user.status !== 'ACTIVE') return json(res, 403, { error: { message: 'This account is inactive.' } }); res.setHeader('Set-Cookie', sessionCookie(sign({ id: user.id }), 604800)); return json(res, 200, { data: { user: publicUser(user) } }) }
  if (req.method === 'POST' && path === '/api/auth/logout') { res.setHeader('Set-Cookie', sessionCookie('', 0)); return json(res, 200, { data: { message: 'Signed out.' } }) }
  if (req.method === 'GET' && path === '/api/auth/me') { const user = userFor(req, store); return user ? json(res, 200, { data: { user: publicUser(user) } }) : json(res, 401, { error: { message: 'Not authenticated.' } }) }
  if (req.method === 'GET' && path === '/api/products') { const search = (url.searchParams.get('search') || '').toLowerCase(); const category = url.searchParams.get('category'); const featured = url.searchParams.get('featured'); let products = store.products.filter(p => p.status === 'ACTIVE' && (!category || p.categoryId === category) && (!featured || p.featured) && (!search || [p.name,p.sku,p.barcode,p.description].join(' ').toLowerCase().includes(search))); const sort = url.searchParams.get('sort'); if (sort === 'price-asc') products.sort((a,b) => (a.salePrice ?? a.sellingPrice)-(b.salePrice ?? b.sellingPrice)); if (sort === 'price-desc') products.sort((a,b) => (b.salePrice ?? b.sellingPrice)-(a.salePrice ?? a.sellingPrice)); const page = Math.max(1, Number(url.searchParams.get('page')) || 1), limit = Math.min(100, Math.max(1, Number(url.searchParams.get('limit')) || 20)); return json(res, 200, { data: products.slice((page-1)*limit, page*limit), meta: { page, limit, total: products.length } }) }
  if (req.method === 'GET' && /^\/api\/products\/[^/]+$/.test(path)) { const product = store.products.find(p => p.id === path.split('/').pop() || p.slug === path.split('/').pop()); return product ? json(res, 200, { data: product }) : json(res, 404, { error: { message: 'Product not found.' } }) }
  if (req.method === 'GET' && path === '/api/categories') return json(res, 200, { data: store.categories.filter(c => c.status === 'ACTIVE') });
  if (req.method === 'GET' && path === '/api/settings') return json(res, 200, { data: store.settings });
  if (req.method === 'GET' && path === '/api/cart') { const user = requireUser(req,res,store); if (!user) return; return json(res, 200, { data: cartView(store, cartFor(store,user)) }) }
  if (req.method === 'POST' && path === '/api/cart/items') { const user = requireUser(req,res,store); if (!user) return; const b = await body(req), product = store.products.find(p => p.id === b.productId && p.status === 'ACTIVE'); if (!product || !Number.isInteger(b.quantity) || b.quantity < 1) return json(res,422,{error:{message:'A valid product and quantity are required.'}}); const cart = cartFor(store,user), item = cart.items.find(i=>i.productId===product.id), next = (item?.quantity||0)+b.quantity; if(next>product.stockQuantity) return json(res,409,{error:{message:'Requested quantity exceeds available stock.'}}); if (item) item.quantity = next; else cart.items.push({id:id(),productId:product.id,quantity:b.quantity}); cart.updatedAt=now(); save(store); return json(res,201,{data:cartView(store,cart)}) }
  if (req.method === 'PUT' && /^\/api\/cart\/items\/[^/]+$/.test(path)) { const user=requireUser(req,res,store); if(!user)return; const b=await body(req), cart=cartFor(store,user), item=cart.items.find(i=>i.id===path.split('/').pop()), product=item&&store.products.find(p=>p.id===item.productId); if(!item||!product)return json(res,404,{error:{message:'Cart item not found.'}}); if(!Number.isInteger(b.quantity)||b.quantity<1||b.quantity>product.stockQuantity)return json(res,422,{error:{message:'Quantity is unavailable.'}}); item.quantity=b.quantity; save(store); return json(res,200,{data:cartView(store,cart)}) }
  if (req.method === 'DELETE' && /^\/api\/cart\/items\/[^/]+$/.test(path)) { const user=requireUser(req,res,store);if(!user)return;const cart=cartFor(store,user);cart.items=cart.items.filter(i=>i.id!==path.split('/').pop());save(store);return json(res,200,{data:cartView(store,cart)}) }
  if (req.method === 'DELETE' && path === '/api/cart') { const user=requireUser(req,res,store);if(!user)return;const cart=cartFor(store,user);cart.items=[];save(store);return json(res,200,{data:cartView(store,cart)}) }
  if (req.method === 'POST' && path === '/api/orders') { const user=requireUser(req,res,store);if(!user)return;const b=await body(req);if(!b.customerName?.trim()||!b.email?.trim()||!b.phone?.trim()||!b.shippingAddress?.trim()||!b.city?.trim()||!b.postalCode?.trim()||b.paymentMethod!=='COD')return json(res,422,{error:{message:'Complete shipping details and Cash on Delivery are required.'}});const cart=cartFor(store,user);if(!cart.items.length)return json(res,422,{error:{message:'Your cart is empty.'}});const calculated=totals(store,cart,b.couponCode);for(const line of calculated.items){line.product.stockQuantity-=line.quantity;store.inventory.push({id:id(),productId:line.product.id,previousQuantity:line.product.stockQuantity+line.quantity,change:-line.quantity,newQuantity:line.product.stockQuantity,reason:'Order placed',userId:user.id,createdAt:now()})}if(calculated.coupon)calculated.coupon.usedCount++;const order={id:id(),orderNumber:orderNumber(),customerId:user.id,customerName:b.customerName.trim(),email:b.email.trim(),phone:b.phone.trim(),shippingAddress:b.shippingAddress.trim(),city:b.city.trim(),postalCode:b.postalCode.trim(),country:b.country?.trim()||'',subtotal:calculated.subtotal,tax:calculated.tax,shippingFee:calculated.shippingFee,discount:calculated.discount,total:calculated.total,paymentMethod:'COD',paymentStatus:'PENDING',orderStatus:'PENDING',notes:b.notes?.trim()||'',items:calculated.items.map(x=>({id:id(),productId:x.product.id,productName:x.product.name,quantity:x.quantity,price:x.price,tax:x.tax})),createdAt:now(),updatedAt:now()};store.orders.push(order);store.payments.push({id:id(),orderId:order.id,provider:'COD',status:'PENDING',amount:order.total,createdAt:now()});cart.items=[];save(store);return json(res,201,{data:order}) }
  if (req.method === 'GET' && path === '/api/orders') { const user=requireUser(req,res,store);if(!user)return;return json(res,200,{data:user.role==='ADMIN'?store.orders:store.orders.filter(o=>o.customerId===user.id)}) }
  if (req.method === 'GET' && /^\/api\/orders\/[^/]+$/.test(path)) { const user=requireUser(req,res,store);if(!user)return;const order=store.orders.find(o=>o.id===path.split('/').pop());return order&&(user.role==='ADMIN'||order.customerId===user.id)?json(res,200,{data:order}):json(res,404,{error:{message:'Order not found.'}}) }
  if (req.method === 'POST' && /^\/api\/orders\/[^/]+\/cancel$/.test(path)) { const user=requireUser(req,res,store);if(!user)return;const order=store.orders.find(o=>o.id===path.split('/')[3]);if(!order||(user.role!=='ADMIN'&&order.customerId!==user.id))return json(res,404,{error:{message:'Order not found.'}});if(['SHIPPED','DELIVERED','CANCELLED'].includes(order.orderStatus))return json(res,409,{error:{message:'This order cannot be cancelled.'}});order.orderStatus='CANCELLED';order.updatedAt=now();for(const line of order.items){const p=store.products.find(p=>p.id===line.productId);if(p){p.stockQuantity+=line.quantity;store.inventory.push({id:id(),productId:p.id,previousQuantity:p.stockQuantity-line.quantity,change:line.quantity,newQuantity:p.stockQuantity,reason:'Order cancelled',userId:user.id,createdAt:now()})}}save(store);return json(res,200,{data:order}) }
  if (req.method === 'GET' && path === '/api/admin/dashboard') { const user=requireUser(req,res,store,true);if(!user)return;const active=store.orders.filter(o=>o.orderStatus!=='CANCELLED');const today=new Date().toDateString();return json(res,200,{data:{totalSales:active.reduce((s,o)=>s+o.total,0),todaySales:active.filter(o=>new Date(o.createdAt).toDateString()===today).reduce((s,o)=>s+o.total,0),totalOrders:store.orders.length,pendingOrders:store.orders.filter(o=>o.orderStatus==='PENDING').length,totalProducts:store.products.length,lowStock:store.products.filter(p=>p.stockQuantity>0&&p.stockQuantity<=p.lowStockThreshold).length,outOfStock:store.products.filter(p=>p.stockQuantity===0).length,totalCustomers:store.users.filter(u=>u.role==='CUSTOMER').length}}) }
  // Admin management endpoints for resources with safe generic CRUD validation.
  if (path === '/api/products' && req.method === 'POST') { const user=requireUser(req,res,store,true);if(!user)return;const b=await body(req);if(!b.name?.trim()||!b.sku?.trim()||!b.categoryId||!Number.isFinite(b.sellingPrice)||!Number.isInteger(b.stockQuantity))return json(res,422,{error:{message:'Product name, SKU, category, price, and integer stock are required.'}});if(store.products.some(p=>p.sku===b.sku))return json(res,409,{error:{message:'SKU already exists.'}});const p={id:id(),name:b.name.trim(),slug:(b.slug||b.name).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''),sku:b.sku.trim(),barcode:b.barcode||'',description:b.description||'',categoryId:b.categoryId,costPrice:Number(b.costPrice||0),sellingPrice:Number(b.sellingPrice),salePrice:b.salePrice==null?null:Number(b.salePrice),taxRate:Number(b.taxRate||0),stockQuantity:b.stockQuantity,lowStockThreshold:Number(b.lowStockThreshold||0),status:b.status||'ACTIVE',featured:Boolean(b.featured),images:Array.isArray(b.images)?b.images:[],createdAt:now(),updatedAt:now()};store.products.push(p);save(store);return json(res,201,{data:p}) }
  if (/^\/api\/products\/[^/]+$/.test(path) && ['PUT','DELETE'].includes(req.method)) { const user=requireUser(req,res,store,true);if(!user)return;const index=store.products.findIndex(p=>p.id===path.split('/').pop());if(index<0)return json(res,404,{error:{message:'Product not found.'}});if(req.method==='DELETE'){store.products[index].status='ARCHIVED';store.products[index].updatedAt=now();save(store);return json(res,200,{data:{message:'Product archived.'}})}const b=await body(req);const allowed=['name','description','categoryId','barcode','costPrice','sellingPrice','salePrice','taxRate','stockQuantity','lowStockThreshold','status','featured','images'];Object.assign(store.products[index],Object.fromEntries(Object.entries(b).filter(([k])=>allowed.includes(k))),{updatedAt:now()});save(store);return json(res,200,{data:store.products[index]}) }
  if (path === '/api/categories' && req.method === 'POST') { const user=requireUser(req,res,store,true);if(!user)return;const b=await body(req);if(!b.name?.trim())return json(res,422,{error:{message:'Category name is required.'}});const category={id:id(),name:b.name.trim(),slug:(b.slug||b.name).toLowerCase().replace(/[^a-z0-9]+/g,'-'),description:b.description||'',image:b.image||'',status:b.status||'ACTIVE',createdAt:now(),updatedAt:now()};store.categories.push(category);save(store);return json(res,201,{data:category}) }
  if (/^\/api\/categories\/[^/]+$/.test(path) && ['PUT','DELETE'].includes(req.method)) { const user=requireUser(req,res,store,true);if(!user)return;const category=store.categories.find(c=>c.id===path.split('/').pop());if(!category)return json(res,404,{error:{message:'Category not found.'}});if(req.method==='DELETE'){if(store.products.some(p=>p.categoryId===category.id))return json(res,409,{error:{message:'Reassign products before deleting this category.'}});store.categories=store.categories.filter(c=>c!==category);save(store);return json(res,200,{data:{message:'Category deleted.'}})}Object.assign(category,await body(req),{updatedAt:now()});save(store);return json(res,200,{data:category}) }
  if (path === '/api/coupons' && req.method === 'GET') { const user=requireUser(req,res,store,true);if(!user)return;return json(res,200,{data:store.coupons}) }
  if (path === '/api/coupons' && req.method === 'POST') { const user=requireUser(req,res,store,true);if(!user)return;const b=await body(req);if(!b.code||!['PERCENTAGE','FIXED'].includes(b.type)||!Number.isFinite(b.value)||!b.startDate||!b.endDate)return json(res,422,{error:{message:'Valid coupon fields are required.'}});const c={id:id(),code:b.code.toUpperCase(),type:b.type,value:b.value,minimumOrder:Number(b.minimumOrder||0),maximumDiscount:b.maximumDiscount?Number(b.maximumDiscount):null,startDate:b.startDate,endDate:b.endDate,usageLimit:b.usageLimit?Number(b.usageLimit):null,usedCount:0,status:b.status||'ACTIVE'};store.coupons.push(c);save(store);return json(res,201,{data:c}) }
  if (path === '/api/settings' && req.method === 'PUT') { const user=requireUser(req,res,store,true);if(!user)return;const b=await body(req);Object.assign(store.settings,b);save(store);return json(res,200,{data:store.settings}) }
  return json(res,404,{error:{message:'Route not found.'}})
 } catch (error) { return json(res, error.message?.includes('stock')||error.message?.includes('Coupon')?409:400, { error:{message:error.message||'Request could not be completed.'} }) }
 }; run()
}
if (import.meta.url === `file://${process.argv[1]}`) createServer(app).listen(PORT, () => console.log(`API listening on http://localhost:${PORT}`))
