import { useMemo, useState } from 'react'
import { Badge, Button, Card, FormGroup, Input, Label, Select, Table, type TableRow } from '../components/ui'
import type { Account, AccountStatus, AccountType, Customer, Transaction } from '../types/bank'
import { formatCurrency, formatDate, formatDateTime, normalise } from '../utils/format'

const statusTone: Record<AccountStatus, 'green' | 'amber' | 'red'> = { active: 'green', dormant: 'amber', closed: 'red' }

export const AccountsPage = ({ accounts, canManage, customers, onOpenAccount, onSelectAccount, onStatusChange, selectedAccountId, transactions }: { accounts: Account[]; customers: Customer[]; transactions: Transaction[]; canManage: boolean; selectedAccountId?: string; onSelectAccount: (accountId: string) => void; onOpenAccount: (payload: Pick<Account, 'customerId' | 'type' | 'openingBalance' | 'status' | 'interestRate'>) => void; onStatusChange: (accountId: string, status: AccountStatus) => void }) => {
  const [search, setSearch] = useState('')
  const [typeFilter, setTypeFilter] = useState<'all' | AccountType>('all')
  const [statusFilter, setStatusFilter] = useState<'all' | AccountStatus>('all')
  const [error, setError] = useState('')
  const [form, setForm] = useState({ customerId: '', type: 'current' as AccountType, openingBalance: '0', status: 'active' as AccountStatus, interestRate: '7' })
  const filteredAccounts = useMemo(() => accounts.filter((account) => { const customer = customers.find((item) => item.id === account.customerId); const term = normalise(search); const matchesSearch = !term || [account.accountNumber, customer?.name ?? '', customer?.cnic ?? ''].some((value) => normalise(value).includes(term)); const matchesType = typeFilter === 'all' || account.type === typeFilter; const matchesStatus = statusFilter === 'all' || account.status === statusFilter; return matchesSearch && matchesType && matchesStatus }), [accounts, customers, search, typeFilter, statusFilter])
  const selectedAccount = accounts.find((account) => account.id === selectedAccountId) ?? filteredAccounts[0] ?? null
  const statementRows: TableRow[] = transactions.filter((transaction) => transaction.accountId === selectedAccount?.id).slice(0, 8).map((transaction) => ({ id: transaction.id, raw: { createdAt: transaction.createdAt, amount: transaction.amount }, cells: { createdAt: formatDateTime(transaction.createdAt), transactionId: transaction.transactionId, type: transaction.type, amount: formatCurrency(transaction.amount), balanceAfter: formatCurrency(transaction.balanceAfter) } }))
  const rows: TableRow[] = filteredAccounts.map((account) => { const customer = customers.find((item) => item.id === account.customerId); return { id: account.id, raw: { accountNumber: account.accountNumber, balance: account.balance }, cells: { accountNumber: <button className="font-semibold text-blue-700 hover:underline" onClick={() => onSelectAccount(account.id)} type="button">{account.accountNumber}</button>, customer: customer?.name ?? 'Unknown', type: account.type, status: <Badge tone={statusTone[account.status]}>{account.status}</Badge>, balance: formatCurrency(account.balance), createdAt: formatDate(account.createdAt) } } })
  return (
    <div className="space-y-6">
      <div className="grid gap-6 xl:grid-cols-[1.1fr,0.9fr]">
        <Card>
          <div className="mb-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h3 className="text-lg font-semibold text-slate-900">Accounts Register</h3><p className="text-sm text-slate-500">Open, review, and maintain branch account records.</p></div><div className="grid gap-3 sm:grid-cols-3"><Input placeholder="Search account or customer" value={search} onChange={(event) => setSearch(event.target.value)} /><Select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value as 'all' | AccountType)}><option value="all">All types</option><option value="current">Current</option><option value="savings">Savings</option></Select><Select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as 'all' | AccountStatus)}><option value="all">All statuses</option><option value="active">Active</option><option value="dormant">Dormant</option><option value="closed">Closed</option></Select></div></div>
          <Table columns={[{ key: 'accountNumber', label: 'Account Number' }, { key: 'customer', label: 'Customer', sortable: true }, { key: 'type', label: 'Type' }, { key: 'status', label: 'Status' }, { key: 'balance', label: 'Balance', sortable: true }, { key: 'createdAt', label: 'Opened', sortable: true }]} emptyMessage="No accounts match the current filters." rows={rows} />
        </Card>
        <div className="space-y-6">
          {canManage ? <Card><h3 className="text-lg font-semibold text-slate-900">Open New Account</h3><form className="mt-4 grid gap-4" onSubmit={(event) => { event.preventDefault(); try { onOpenAccount({ customerId: form.customerId, type: form.type, openingBalance: Number(form.openingBalance), status: form.status, interestRate: form.type === 'savings' ? Number(form.interestRate) : undefined }); setForm({ customerId: '', type: 'current', openingBalance: '0', status: 'active', interestRate: '7' }); setError('') } catch (caughtError) { setError(caughtError instanceof Error ? caughtError.message : 'Unable to open account.') } }}><FormGroup><Label>Customer</Label><Select value={form.customerId} onChange={(event) => setForm((current) => ({ ...current, customerId: event.target.value }))}><option value="">Select customer</option>{customers.map((customer) => <option disabled={customer.status !== 'active'} key={customer.id} value={customer.id}>{customer.name} ({customer.status})</option>)}</Select></FormGroup><div className="grid gap-4 sm:grid-cols-2"><FormGroup><Label>Account Type</Label><Select value={form.type} onChange={(event) => setForm((current) => ({ ...current, type: event.target.value as AccountType }))}><option value="current">Current</option><option value="savings">Savings</option></Select></FormGroup><FormGroup><Label>Status</Label><Select value={form.status} onChange={(event) => setForm((current) => ({ ...current, status: event.target.value as AccountStatus }))}><option value="active">Active</option><option value="dormant">Dormant</option></Select></FormGroup></div><div className="grid gap-4 sm:grid-cols-2"><FormGroup><Label>Opening Balance</Label><Input min="0" step="0.01" type="number" value={form.openingBalance} onChange={(event) => setForm((current) => ({ ...current, openingBalance: event.target.value }))} /></FormGroup>{form.type === 'savings' ? <FormGroup><Label>Interest Rate (%)</Label><Input min="0" step="0.1" type="number" value={form.interestRate} onChange={(event) => setForm((current) => ({ ...current, interestRate: event.target.value }))} /></FormGroup> : null}</div>{error ? <p className="rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}<Button type="submit">Open Account</Button></form></Card> : null}
          {selectedAccount ? <Card><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs uppercase tracking-wide text-slate-400">Selected account</p><h3 className="mt-2 text-lg font-semibold text-slate-900">{selectedAccount.accountNumber}</h3><p className="text-sm text-slate-500">{customers.find((customer) => customer.id === selectedAccount.customerId)?.name}</p><p className="mt-3 text-2xl font-semibold text-slate-900">{formatCurrency(selectedAccount.balance)}</p></div>{canManage ? <div className="flex gap-3"><Button type="button" variant="secondary" onClick={() => onStatusChange(selectedAccount.id, 'dormant')}>Set Dormant</Button><Button type="button" variant="danger" onClick={() => onStatusChange(selectedAccount.id, 'closed')}>Close Account</Button></div> : null}</div><div className="mt-6"><h4 className="mb-3 text-sm font-semibold text-slate-900">Mini Statement</h4><Table columns={[{ key: 'createdAt', label: 'Date', sortable: true }, { key: 'transactionId', label: 'Transaction ID' }, { key: 'type', label: 'Type' }, { key: 'amount', label: 'Amount', sortable: true }, { key: 'balanceAfter', label: 'Balance After' }]} emptyMessage="No transactions recorded for this account yet." rows={statementRows} /></div></Card> : null}
        </div>
      </div>
    </div>
  )
}
