import { useMemo, useState } from 'react'
import { Badge, Button, Card, FormGroup, Input, Label, Select, Table, Textarea, type TableRow } from '../components/ui'
import type { Account, Customer, ServiceRequest, ServiceRequestStatus, Transaction } from '../types/bank'
import { formatCurrency, formatDateTime, normalise } from '../utils/format'

const statusTone: Record<ServiceRequestStatus, 'amber' | 'blue' | 'green'> = { open: 'amber', in_progress: 'blue', resolved: 'green' }

export const CsrPage = ({ accounts, customers, onAddRequest, onSelectAccount, onSelectCustomer, onUpdateStatus, selectedAccountId, selectedCustomerId, serviceRequests, transactions }: { customers: Customer[]; accounts: Account[]; transactions: Transaction[]; serviceRequests: ServiceRequest[]; selectedCustomerId?: string; selectedAccountId?: string; onSelectCustomer: (customerId: string) => void; onSelectAccount: (accountId: string) => void; onAddRequest: (payload: Pick<ServiceRequest, 'customerId' | 'type' | 'subject' | 'description'>) => void; onUpdateStatus: (requestId: string, status: ServiceRequestStatus) => void }) => {
  const [search, setSearch] = useState('')
  const [form, setForm] = useState({ customerId: selectedCustomerId ?? '', type: 'complaint' as ServiceRequest['type'], subject: '', description: '' })
  const [error, setError] = useState('')
  const filteredCustomers = useMemo(() => customers.filter((customer) => !search || [customer.name, customer.cnic, customer.phone].some((value) => normalise(value).includes(normalise(search)))), [customers, search])
  const selectedCustomer = customers.find((customer) => customer.id === selectedCustomerId) ?? filteredCustomers[0] ?? null
  const linkedAccounts = accounts.filter((account) => account.customerId === selectedCustomer?.id)
  const selectedAccount = linkedAccounts.find((account) => account.id === selectedAccountId) ?? linkedAccounts[0] ?? null
  const statementRows: TableRow[] = transactions.filter((transaction) => selectedAccount ? transaction.accountId === selectedAccount.id : selectedCustomer ? accounts.find((account) => account.id === transaction.accountId)?.customerId === selectedCustomer.id : false).slice(0, 10).map((transaction) => ({ id: transaction.id, raw: { createdAt: transaction.createdAt }, cells: { transactionId: transaction.transactionId, createdAt: formatDateTime(transaction.createdAt), type: transaction.type, amount: formatCurrency(transaction.amount), balanceAfter: formatCurrency(transaction.balanceAfter) } }))
  const requestRows: TableRow[] = serviceRequests.map((request) => ({ id: request.id, raw: { createdAt: request.createdAt }, cells: { customer: customers.find((customer) => customer.id === request.customerId)?.name ?? 'Unknown', type: request.type, subject: request.subject, status: <Badge tone={statusTone[request.status]}>{request.status}</Badge>, createdAt: formatDateTime(request.createdAt), actions: <Select value={request.status} onChange={(event) => onUpdateStatus(request.id, event.target.value as ServiceRequestStatus)}><option value="open">Open</option><option value="in_progress">In Progress</option><option value="resolved">Resolved</option></Select> } }))
  return (
    <div className="space-y-6">
      <div className="grid gap-6 xl:grid-cols-[0.9fr,1.1fr]">
        <div className="space-y-6">
          <Card><h3 className="text-lg font-semibold text-slate-900">Customer Search</h3><Input className="mt-4" placeholder="Search by name, CNIC, or phone" value={search} onChange={(event) => setSearch(event.target.value)} /><div className="mt-4 space-y-3">{filteredCustomers.map((customer) => <button className="block w-full rounded-2xl border border-slate-200 p-4 text-left hover:border-blue-200 hover:bg-blue-50" key={customer.id} onClick={() => { onSelectCustomer(customer.id); setForm((current) => ({ ...current, customerId: customer.id })) }} type="button"><p className="font-semibold text-slate-900">{customer.name}</p><p className="text-sm text-slate-500">{customer.cnic} · {customer.phone}</p></button>)}</div></Card>
          <Card><h3 className="text-lg font-semibold text-slate-900">Create Complaint / Request</h3><form className="mt-4 grid gap-4" onSubmit={(event) => { event.preventDefault(); try { onAddRequest(form); setForm({ customerId: selectedCustomer?.id ?? '', type: 'complaint', subject: '', description: '' }); setError('') } catch (caughtError) { setError(caughtError instanceof Error ? caughtError.message : 'Unable to create request.') } }}><FormGroup><Label>Customer</Label><Select value={form.customerId} onChange={(event) => setForm((current) => ({ ...current, customerId: event.target.value }))}><option value="">Select customer</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</Select></FormGroup><FormGroup><Label>Type</Label><Select value={form.type} onChange={(event) => setForm((current) => ({ ...current, type: event.target.value as ServiceRequest['type'] }))}><option value="complaint">Complaint</option><option value="request">Request</option></Select></FormGroup><FormGroup><Label>Subject</Label><Input value={form.subject} onChange={(event) => setForm((current) => ({ ...current, subject: event.target.value }))} /></FormGroup><FormGroup><Label>Description</Label><Textarea value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} /></FormGroup>{error ? <p className="rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}<Button type="submit">Create Ticket</Button></form></Card>
        </div>
        <div className="space-y-6">
          <Card><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><h3 className="text-lg font-semibold text-slate-900">Balance Inquiry</h3>{selectedCustomer ? <><p className="mt-2 text-base font-semibold text-slate-900">{selectedCustomer.name}</p><p className="text-sm text-slate-500">{selectedCustomer.cnic} · {selectedCustomer.address}</p></> : <p className="mt-2 text-sm text-slate-500">Select a customer to view linked account information.</p>}</div>{linkedAccounts.length ? <Select value={selectedAccount?.id ?? ''} onChange={(event) => onSelectAccount(event.target.value)}>{linkedAccounts.map((account) => <option key={account.id} value={account.id}>{account.accountNumber}</option>)}</Select> : null}</div>{selectedAccount ? <div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs uppercase tracking-wide text-slate-400">Account</p><p className="mt-2 font-semibold text-slate-900">{selectedAccount.accountNumber}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs uppercase tracking-wide text-slate-400">Status</p><p className="mt-2 font-semibold text-slate-900">{selectedAccount.status}</p></div><div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs uppercase tracking-wide text-blue-700">Balance</p><p className="mt-2 text-xl font-semibold text-blue-900">{formatCurrency(selectedAccount.balance)}</p></div></div> : null}</Card>
          <Card><h3 className="mb-4 text-lg font-semibold text-slate-900">Transaction Inquiry</h3><Table columns={[{ key: 'transactionId', label: 'Transaction ID' }, { key: 'createdAt', label: 'Date', sortable: true }, { key: 'type', label: 'Type' }, { key: 'amount', label: 'Amount' }, { key: 'balanceAfter', label: 'Balance After' }]} emptyMessage="No transactions available for the selected customer/account." rows={statementRows} /></Card>
          <Card><h3 className="mb-4 text-lg font-semibold text-slate-900">Complaints & Requests</h3><Table columns={[{ key: 'customer', label: 'Customer' }, { key: 'type', label: 'Type' }, { key: 'subject', label: 'Subject' }, { key: 'status', label: 'Status' }, { key: 'createdAt', label: 'Created', sortable: true }, { key: 'actions', label: 'Update' }]} emptyMessage="No service tickets have been recorded yet." rows={requestRows} /></Card>
        </div>
      </div>
    </div>
  )
}
