import { useEffect, useMemo, useState } from 'react'
import { Badge, Button, Card, FormGroup, Input, Label, Select, Table, Textarea, type TableRow } from '../components/ui'
import type { Account, Customer, CustomerStatus } from '../types/bank'
import { formatDate, normalise } from '../utils/format'

const statusTone: Record<CustomerStatus, 'green' | 'amber' | 'red'> = { active: 'green', inactive: 'amber', suspended: 'red' }

export const CustomersPage = ({ accounts, canEdit, customers, onAddCustomer, onSelectCustomer, onUpdateCustomer, selectedCustomerId, requestStatusChange }: { customers: Customer[]; accounts: Account[]; canEdit: boolean; selectedCustomerId?: string; onSelectCustomer: (customerId: string) => void; onAddCustomer: (payload: Omit<Customer, 'id' | 'createdAt'>) => void; onUpdateCustomer: (customerId: string, payload: Pick<Customer, 'name' | 'phone' | 'address' | 'status'>) => void; requestStatusChange: (customerId: string, status: CustomerStatus) => void }) => {
  const [search, setSearch] = useState('')
  const [statusFilter, setStatusFilter] = useState<'all' | CustomerStatus>('all')
  const [error, setError] = useState('')
  const [form, setForm] = useState<Omit<Customer, 'id' | 'createdAt'>>({ cnic: '', name: '', fatherName: '', dob: '', phone: '', address: '', status: 'active' })
  const filteredCustomers = useMemo(() => customers.filter((customer) => { const term = normalise(search); const matchesSearch = !term || [customer.id, customer.cnic, customer.name, customer.phone].some((value) => normalise(value).includes(term)); const matchesStatus = statusFilter === 'all' || customer.status === statusFilter; return matchesSearch && matchesStatus }), [customers, search, statusFilter])
  const selectedCustomer = customers.find((customer) => customer.id === selectedCustomerId) ?? filteredCustomers[0] ?? null
  const [editForm, setEditForm] = useState({ name: '', phone: '', address: '', status: 'active' as CustomerStatus })
  useEffect(() => { if (selectedCustomer) setEditForm({ name: selectedCustomer.name, phone: selectedCustomer.phone, address: selectedCustomer.address, status: selectedCustomer.status }) }, [selectedCustomer])
  const rows: TableRow[] = filteredCustomers.map((customer) => ({ id: customer.id, raw: { name: customer.name, createdAt: customer.createdAt }, cells: { id: <button className="font-semibold text-blue-700 hover:underline" onClick={() => onSelectCustomer(customer.id)} type="button">{customer.id}</button>, cnic: customer.cnic, name: customer.name, phone: customer.phone, status: <Badge tone={statusTone[customer.status]}>{customer.status}</Badge>, createdAt: formatDate(customer.createdAt) } }))
  return (
    <div className="space-y-6">
      <div className="grid gap-6 xl:grid-cols-[1.15fr,0.85fr]">
        <Card>
          <div className="mb-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h3 className="text-lg font-semibold text-slate-900">Customer Directory</h3><p className="text-sm text-slate-500">Search by customer ID, CNIC, name, or phone.</p></div><div className="grid gap-3 sm:grid-cols-2"><Input placeholder="Search customers" value={search} onChange={(event) => setSearch(event.target.value)} /><Select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as 'all' | CustomerStatus)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></Select></div></div>
          <Table columns={[{ key: 'id', label: 'Customer ID' }, { key: 'cnic', label: 'CNIC', sortable: true }, { key: 'name', label: 'Name', sortable: true }, { key: 'phone', label: 'Phone' }, { key: 'status', label: 'Status' }, { key: 'createdAt', label: 'Created', sortable: true }]} emptyMessage="No customers match the selected search and status filters." rows={rows} />
        </Card>
        <div className="space-y-6">
          <Card>
            <h3 className="text-lg font-semibold text-slate-900">{canEdit ? 'Add Customer' : 'Customer Details'}</h3>{!canEdit ? <p className="mt-2 text-sm text-slate-500">CSR users can view customer data only.</p> : null}
            {canEdit ? <form className="mt-4 grid gap-4" onSubmit={(event) => { event.preventDefault(); try { onAddCustomer(form); setForm({ cnic: '', name: '', fatherName: '', dob: '', phone: '', address: '', status: 'active' }); setError('') } catch (caughtError) { setError(caughtError instanceof Error ? caughtError.message : 'Unable to add customer.') } }}><FormGroup><Label>CNIC</Label><Input maxLength={13} placeholder="13 digit CNIC" value={form.cnic} onChange={(event) => setForm((current) => ({ ...current, cnic: event.target.value }))} /></FormGroup><div className="grid gap-4 sm:grid-cols-2"><FormGroup><Label>Name</Label><Input value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} /></FormGroup><FormGroup><Label>Father Name</Label><Input value={form.fatherName} onChange={(event) => setForm((current) => ({ ...current, fatherName: event.target.value }))} /></FormGroup></div><div className="grid gap-4 sm:grid-cols-2"><FormGroup><Label>Date of Birth</Label><Input type="date" value={form.dob} onChange={(event) => setForm((current) => ({ ...current, dob: event.target.value }))} /></FormGroup><FormGroup><Label>Phone</Label><Input value={form.phone} onChange={(event) => setForm((current) => ({ ...current, phone: event.target.value }))} /></FormGroup></div><FormGroup><Label>Address</Label><Textarea value={form.address} onChange={(event) => setForm((current) => ({ ...current, address: event.target.value }))} /></FormGroup><FormGroup><Label>Status</Label><Select value={form.status} onChange={(event) => setForm((current) => ({ ...current, status: event.target.value as CustomerStatus }))}><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></Select></FormGroup>{error ? <p className="rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}<Button type="submit">Save Customer</Button></form> : selectedCustomer ? <div className="mt-4 space-y-3 text-sm text-slate-600"><p><span className="font-semibold text-slate-900">ID:</span> {selectedCustomer.id}</p><p><span className="font-semibold text-slate-900">CNIC:</span> {selectedCustomer.cnic}</p><p><span className="font-semibold text-slate-900">Name:</span> {selectedCustomer.name}</p><p><span className="font-semibold text-slate-900">Phone:</span> {selectedCustomer.phone}</p><p><span className="font-semibold text-slate-900">Address:</span> {selectedCustomer.address}</p></div> : null}
          </Card>
          {selectedCustomer ? <Card><div className="grid gap-4 sm:grid-cols-2"><div><p className="text-xs uppercase tracking-wide text-slate-400">Profile</p><p className="mt-2 text-lg font-semibold text-slate-900">{selectedCustomer.name}</p><p className="text-sm text-slate-500">{selectedCustomer.cnic}</p><p className="mt-2 text-sm text-slate-600">{selectedCustomer.address}</p><p className="mt-1 text-sm text-slate-600">Accounts: {accounts.filter((account) => account.customerId === selectedCustomer.id).length}</p></div>{canEdit ? <form className="space-y-3" onSubmit={(event) => { event.preventDefault(); try { onUpdateCustomer(selectedCustomer.id, editForm); setError('') } catch (caughtError) { setError(caughtError instanceof Error ? caughtError.message : 'Unable to update customer.') } }}><FormGroup><Label>Name</Label><Input value={editForm.name} onChange={(event) => setEditForm((current) => ({ ...current, name: event.target.value }))} /></FormGroup><FormGroup><Label>Phone</Label><Input value={editForm.phone} onChange={(event) => setEditForm((current) => ({ ...current, phone: event.target.value }))} /></FormGroup><FormGroup><Label>Address</Label><Textarea value={editForm.address} onChange={(event) => setEditForm((current) => ({ ...current, address: event.target.value }))} /></FormGroup><FormGroup><Label>Status</Label><Select value={editForm.status} onChange={(event) => setEditForm((current) => ({ ...current, status: event.target.value as CustomerStatus }))}><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></Select></FormGroup><div className="flex flex-wrap gap-3"><Button type="submit">Update Customer</Button><Button type="button" variant="secondary" onClick={() => requestStatusChange(selectedCustomer.id, 'inactive')}>Deactivate</Button><Button type="button" variant="danger" onClick={() => requestStatusChange(selectedCustomer.id, 'suspended')}>Suspend</Button></div></form> : null}</div></Card> : null}
        </div>
      </div>
    </div>
  )
}
