import { useMemo, useState } from 'react'
import { Badge, Button, Card, DateRangePicker, FormGroup, Input, Label, Select, Table, type TableRow } from '../components/ui'
import type { Account, Customer, Transaction } from '../types/bank'
import { formatCurrency, formatDateTime, matchesDateRange, normalise } from '../utils/format'

const transactionTone: Record<Transaction['type'], 'green' | 'red' | 'amber' | 'blue'> = { deposit: 'green', withdrawal: 'red', transfer_out: 'amber', transfer_in: 'blue' }

export const TransactionsPage = ({ accounts, canTransact, customers, onPrintReceipt, onSubmit, preselectedAccountId, preselectedType, transactions }: { accounts: Account[]; customers: Customer[]; transactions: Transaction[]; canTransact: boolean; preselectedType?: 'deposit' | 'withdrawal' | 'transfer'; preselectedAccountId?: string; onSubmit: (payload: { mode: 'deposit' | 'withdrawal' | 'transfer'; accountId?: string; sourceAccountId?: string; destinationAccountId?: string; amount: number; description: string }) => void; onPrintReceipt: (transactionId: string) => void }) => {
  const [mode, setMode] = useState<'deposit' | 'withdrawal' | 'transfer'>(preselectedType ?? 'deposit')
  const [filters, setFilters] = useState({ type: 'all', accountId: '', customerId: '', startDate: '', endDate: '', search: '' })
  const [error, setError] = useState('')
  const [form, setForm] = useState({ accountId: preselectedAccountId ?? '', sourceAccountId: '', destinationAccountId: '', amount: '', description: '' })
  const filteredTransactions = useMemo(() => transactions.filter((transaction) => { const account = accounts.find((item) => item.id === transaction.accountId); const customer = customers.find((item) => item.id === account?.customerId); const term = normalise(filters.search); const matchesSearch = !term || [transaction.transactionId, transaction.description, account?.accountNumber ?? '', customer?.name ?? ''].some((value) => normalise(value).includes(term)); const matchesType = filters.type === 'all' || transaction.type === filters.type; const matchesAccount = !filters.accountId || transaction.accountId === filters.accountId; const matchesCustomer = !filters.customerId || account?.customerId === filters.customerId; return matchesSearch && matchesType && matchesAccount && matchesCustomer && matchesDateRange(transaction.createdAt, filters.startDate, filters.endDate) }), [accounts, customers, filters, transactions])
  const rows: TableRow[] = filteredTransactions.map((transaction) => { const account = accounts.find((item) => item.id === transaction.accountId); const customer = customers.find((item) => item.id === account?.customerId); return { id: transaction.id, raw: { createdAt: transaction.createdAt, amount: transaction.amount }, cells: { transactionId: transaction.transactionId, createdAt: formatDateTime(transaction.createdAt), account: account?.accountNumber ?? 'Unknown', customer: customer?.name ?? 'Unknown', type: <Badge tone={transactionTone[transaction.type]}>{transaction.type}</Badge>, amount: formatCurrency(transaction.amount), balanceAfter: formatCurrency(transaction.balanceAfter), actions: <Button type="button" variant="secondary" size="sm" onClick={() => onPrintReceipt(transaction.id)}>Print Receipt</Button> } } })
  return (
    <div className="space-y-6">
      {canTransact ? <Card><div className="mb-4 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h3 className="text-lg font-semibold text-slate-900">Cash Operations</h3><p className="text-sm text-slate-500">Post deposits, withdrawals, and fund transfers.</p></div><Select value={mode} onChange={(event) => setMode(event.target.value as 'deposit' | 'withdrawal' | 'transfer')}><option value="deposit">Cash Deposit</option><option value="withdrawal">Cash Withdrawal</option><option value="transfer">Fund Transfer</option></Select></div><form className="grid gap-4 lg:grid-cols-2" onSubmit={(event) => { event.preventDefault(); try { onSubmit({ mode, accountId: form.accountId, sourceAccountId: form.sourceAccountId, destinationAccountId: form.destinationAccountId, amount: Number(form.amount), description: form.description }); setForm({ accountId: preselectedAccountId ?? '', sourceAccountId: '', destinationAccountId: '', amount: '', description: '' }); setError('') } catch (caughtError) { setError(caughtError instanceof Error ? caughtError.message : 'Unable to process transaction.') } }}>{mode === 'transfer' ? <><FormGroup><Label>Source Account</Label><Select value={form.sourceAccountId} onChange={(event) => setForm((current) => ({ ...current, sourceAccountId: event.target.value }))}><option value="">Select source account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.accountNumber} ({account.status})</option>)}</Select></FormGroup><FormGroup><Label>Destination Account</Label><Select value={form.destinationAccountId} onChange={(event) => setForm((current) => ({ ...current, destinationAccountId: event.target.value }))}><option value="">Select destination account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.accountNumber} ({account.status})</option>)}</Select></FormGroup></> : <FormGroup><Label>Account</Label><Select value={form.accountId} onChange={(event) => setForm((current) => ({ ...current, accountId: event.target.value }))}><option value="">Select account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.accountNumber} ({account.status})</option>)}</Select></FormGroup>}<FormGroup><Label>Amount</Label><Input min="0" step="0.01" type="number" value={form.amount} onChange={(event) => setForm((current) => ({ ...current, amount: event.target.value }))} /></FormGroup><div className="lg:col-span-2"><FormGroup><Label>Description</Label><Input value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} /></FormGroup></div>{error ? <p className="lg:col-span-2 rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}<div className="lg:col-span-2"><Button type="submit">Process {mode === 'deposit' ? 'Deposit' : mode === 'withdrawal' ? 'Withdrawal' : 'Transfer'}</Button></div></form></Card> : null}
      <Card><div className="mb-4 flex flex-col gap-4"><div><h3 className="text-lg font-semibold text-slate-900">Transaction History</h3><p className="text-sm text-slate-500">Filter by type, date range, account, customer, or free text.</p></div><div className="grid gap-4 lg:grid-cols-4"><Input placeholder="Search transactions" value={filters.search} onChange={(event) => setFilters((current) => ({ ...current, search: event.target.value }))} /><Select value={filters.type} onChange={(event) => setFilters((current) => ({ ...current, type: event.target.value }))}><option value="all">All types</option><option value="deposit">Deposit</option><option value="withdrawal">Withdrawal</option><option value="transfer_out">Transfer out</option><option value="transfer_in">Transfer in</option></Select><Select value={filters.accountId} onChange={(event) => setFilters((current) => ({ ...current, accountId: event.target.value }))}><option value="">All accounts</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.accountNumber}</option>)}</Select><Select value={filters.customerId} onChange={(event) => setFilters((current) => ({ ...current, customerId: event.target.value }))}><option value="">All customers</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</Select></div><DateRangePicker endDate={filters.endDate} onEndDateChange={(value) => setFilters((current) => ({ ...current, endDate: value }))} onStartDateChange={(value) => setFilters((current) => ({ ...current, startDate: value }))} startDate={filters.startDate} /></div><Table columns={[{ key: 'transactionId', label: 'Transaction ID' }, { key: 'createdAt', label: 'Date', sortable: true }, { key: 'account', label: 'Account' }, { key: 'customer', label: 'Customer' }, { key: 'type', label: 'Type' }, { key: 'amount', label: 'Amount', sortable: true }, { key: 'balanceAfter', label: 'Balance After' }, { key: 'actions', label: 'Receipt' }]} emptyMessage="No transactions match the selected filters." rows={rows} /></Card>
    </div>
  )
}
