import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Product = { id:string; name:string; description:string; sku:string; sellingPrice:number; salePrice:number|null; stockQuantity:number; lowStockThreshold:number; categoryId:string; featured:boolean }
type Cart = { items: { id:string; quantity:number; product:Product }[] }
const api = async <T,>(path:string, options:RequestInit = {}) => { const r=await fetch(`/api${path}`, { credentials:'include', headers:{'Content-Type':'application/json', ...(options.headers||{})}, ...options }); const j=await r.json(); if(!r.ok) throw new Error(j.error?.message||'Something went wrong.'); return j.data as T }
const money = (value:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value)

export default function App() {
 const [products,setProducts]=useState<Product[]>([]), [categories,setCategories]=useState<{id:string;name:string}[]>([]), [cart,setCart]=useState<Cart>({items:[]}), [query,setQuery]=useState(''), [message,setMessage]=useState(''), [account,setAccount]=useState<{name:string;email:string;role:string}|null>(null), [showAuth,setShowAuth]=useState(false), [showCheckout,setShowCheckout]=useState(false)
 const load=async()=>{ try { const [p,c]=await Promise.all([api<Product[]>(`/products?search=${encodeURIComponent(query)}&limit=24`),api<{id:string;name:string}[]>('/categories')]);setProducts(p);setCategories(c); } catch(e){setMessage(e instanceof Error?e.message:'Unable to load store.')} }
 useEffect(()=>{load()},[query]); useEffect(()=>{api<Cart>('/cart').then(setCart).catch(()=>undefined);api<{user:{name:string;email:string;role:string}}>('/auth/me').then(x=>setAccount(x.user)).catch(()=>undefined)},[])
 const add=async(productId:string)=>{try{if(!account){setShowAuth(true);return}setCart(await api<Cart>('/cart/items',{method:'POST',body:JSON.stringify({productId,quantity:1})}));setMessage('Added to your cart.')}catch(e){setMessage(e instanceof Error?e.message:'Could not add item.')}}
 const total=useMemo(()=>cart.items.reduce((s,x)=>s+(x.product.salePrice??x.product.sellingPrice)*x.quantity,0),[cart])
 return <main>
  <header className="nav"><a className="brand" href="#top">ITM<span>AN</span>GEMENT</a><nav><a href="#shop">Shop</a><a href="#about">About</a>{account?.role==='ADMIN'&&<a href="/admin">Admin</a>}</nav><div className="nav-actions"><button className="quiet" onClick={()=>setShowAuth(true)}>{account?account.name:'Sign in'}</button><a className="cart-link" href="#cart">Bag <b>{cart.items.length}</b></a></div></header>
  <section id="top" className="hero"><div><p className="overline">Built for better workdays</p><h1>Tools that make space for <em>focus.</em></h1><p className="lede">Curated technology and practical office essentials, delivered with care.</p><a className="button" href="#shop">Explore the collection <span>→</span></a></div><div className="hero-art"><img src="/src/assets/hero.png" alt="A thoughtfully arranged modern workspace"/><div className="hero-note"><small>New collection</small><strong>Intentional objects for everyday work.</strong></div></div></section>
  <section className="benefits"><div><b>01</b><span>Secure checkout</span></div><div><b>02</b><span>Thoughtful selection</span></div><div><b>03</b><span>Support that responds</span></div></section>
  <section id="shop" className="shop"><div className="section-title"><div><p className="overline">Shop the edit</p><h2>Everything in its place.</h2></div><input aria-label="Search products" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products, SKU…" /></div><div className="chips"><button onClick={()=>setQuery('')}>All items</button>{categories.map(c=><button key={c.id} onClick={()=>setQuery(c.name)}>{c.name}</button>)}</div><div className="product-grid">{products.map(p=><article className="product" key={p.id}><div className="product-image"><span>{p.featured?'Featured':'Everyday essential'}</span><div aria-hidden="true">{p.name.slice(0,1)}</div></div><div className="product-content"><p className="sku">{p.sku} · {p.stockQuantity===0?'Out of stock':p.stockQuantity<=p.lowStockThreshold?'Low stock':'In stock'}</p><h3>{p.name}</h3><p>{p.description}</p><div className="product-bottom"><strong>{money(p.salePrice??p.sellingPrice)} {p.salePrice&&<del>{money(p.sellingPrice)}</del>}</strong><button disabled={!p.stockQuantity} onClick={()=>add(p.id)}>{p.stockQuantity?'Add to bag':'Unavailable'}</button></div></div></article>)}</div>{!products.length&&<div className="empty">No products match that search.</div>}</section>
  <section id="cart" className="cart"><div><p className="overline">Your selection</p><h2>Shopping bag</h2></div><div className="cart-lines">{cart.items.length?cart.items.map(i=><div key={i.id}><span>{i.product.name} <small>× {i.quantity}</small></span><b>{money((i.product.salePrice??i.product.sellingPrice)*i.quantity)}</b></div>):<p>Your bag is ready when you are.</p>}</div><div className="cart-total"><span>Items subtotal</span><b>{money(total)}</b></div><button className="button" disabled={!cart.items.length} onClick={()=>setShowCheckout(true)}>Continue to checkout <span>→</span></button></section>
  <footer id="about"><div className="brand">ITM<span>AN</span>GEMENT</div><p>Professional essentials for better work.</p><div><a href="#privacy">Privacy</a><a href="#terms">Terms</a><a href="mailto:hello@example.com">Contact</a></div></footer>
  {message&&<div className="toast" role="status">{message}<button onClick={()=>setMessage('')}>×</button></div>}{showAuth&&<Auth close={()=>setShowAuth(false)} done={(u)=>{setAccount(u);setShowAuth(false);api<Cart>('/cart').then(setCart);setMessage(`Welcome, ${u.name}.`)}}/>}{showCheckout&&<Checkout total={total} close={()=>setShowCheckout(false)} done={(n)=>{setShowCheckout(false);setCart({items:[]});setMessage(`Order ${n} is confirmed. We will contact you to arrange Cash on Delivery.`)}}/>}
 </main>
}
function Auth({close,done}:{close:()=>void;done:(u:{name:string;email:string;role:string})=>void}){const[mode,setMode]=useState<'login'|'register'>('login'),[error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const data=await api<{user:{name:string;email:string;role:string}}>(`/auth/${mode}`,{method:'POST',body:JSON.stringify(Object.fromEntries(f))});done(data.user)}catch(x){setError(x instanceof Error?x.message:'Unable to continue.')}};return <div className="modal"><form className="dialog" onSubmit={submit}><button className="close" type="button" onClick={close}>×</button><p className="overline">Your account</p><h2>{mode==='login'?'Welcome back':'Create an account'}</h2>{mode==='register'&&<input name="name" placeholder="Full name" required/>}<input name="email" type="email" placeholder="Email address" required/><input name="password" type="password" minLength={8} placeholder="Password (8+ characters)" required/>{error&&<p className="error">{error}</p>}<button className="button">{mode==='login'?'Sign in':'Create account'} <span>→</span></button><button type="button" className="quiet switch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Need an account? Register':'Already registered? Sign in'}</button></form></div>}
function Checkout({total,close,done}:{total:number;close:()=>void;done:(n:string)=>void}){const[error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();try{const data=await api<{orderNumber:string}>('/orders',{method:'POST',body:JSON.stringify({...Object.fromEntries(new FormData(e.currentTarget)),paymentMethod:'COD'})});done(data.orderNumber)}catch(x){setError(x instanceof Error?x.message:'Unable to place order.')}};return <div className="modal"><form className="dialog checkout" onSubmit={submit}><button className="close" type="button" onClick={close}>×</button><p className="overline">Checkout · {money(total)}</p><h2>Delivery details</h2><input name="customerName" placeholder="Full name" required/><input name="email" type="email" placeholder="Email address" required/><input name="phone" placeholder="Phone number" required/><input name="shippingAddress" placeholder="Street address" required/><div className="two"><input name="city" placeholder="City" required/><input name="postalCode" placeholder="Postal code" required/></div><input name="country" placeholder="Country" defaultValue="Pakistan" required/><textarea name="notes" placeholder="Order notes (optional)"/>{error&&<p className="error">{error}</p>}<p className="cod">Payment: <b>Cash on Delivery</b>. Your final total is securely calculated by the server.</p><button className="button">Place order <span>→</span></button></form></div>}
